version: '3.8'
services:
  web:
    build: .
    command: gunicorn csvapi.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - mypostgres
      - myredis

  celery:
    build: .
    command: celery -A csvapi worker --loglevel=info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - myredis
      - mypostgres

  mypostgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  myredis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
